ACTION_NAMES = {
    1: "waitUntilNoEnemies",
    2: "requirePlayers",
    3: "unknownAction3",
    4: "goToNextArea",
    5: "unknownAction5",
    6: "loopCodeFromZero",
    7: "skyGradient",
    8: "waterNormal",
    9: "waterLava",
    10: "waterAlien",
    11: "snowNormal",
    12: "snowAsh",
    13: "snowRain",
    14: "spawnPlanet",
    15: "stopTiles",
    16: "waitForHillPop",
    17: "randomTiles",
    18: "forceTile",
    19: "unknownAction19",
    20: "unknownAction20",
    21: "spawnFormation",
    22: "spawnEnemy",
    23: "spawnScenery",
    24: "balloonCrateCoins",
    25: "balloonCrateDoublePoints",
    26: "balloonCrateWeaponPods",
    27: "balloonCrateShield",
    28: "balloonCrateExtraLife",
    29: "balloonCrateLightningStar"
}

ACTION_ARG_NAMES = {
    2: ["minPlayers"],
    7: ["startPoint", "scrollSpeed"],
    8: ["type"],
    9: ["type"],
    10: ["type"],
    11: ["intensity"],
    12: ["intensity"],
    13: ["intensity"],
    14: ["sprite", "xPos", "yPos", "ySpeed"],
    15: ["layer"],
    16: ["layer"],
    17: ["layer", "tileMin", "tileMax"],
    18: ["layer", "tile"],
    21: ["object", "formation", "yPos", "bonus"],
    22: ["object"],
    23: ["object"]
}

ENEMY_NAMES = {
    1: "bullet",
    2: "flame",
    3: "missile",
    4: "laser",
    5: "orb",
    6: "glob",
    7: "bomb",
    8: "bombfrag",
    9: "mine",
    10: "rock",
    11: "unknownEnemy11",
    12: "unknownEnemy12",
    13: "unknownEnemy13",
    14: "flamejet",
    15: "buoy",
    16: "dish",
    17: "building",
    18: "tank",
    19: "wallgun",
    20: "icbm",
    21: "domeship",
    22: "domeship2",
    23: "saucer",
    24: "saucer2",
    25: "saucer_red",
    26: "zipper",
    27: "fish",
    28: "fish_red",
    29: "fish_green",
    30: "horseshoe",
    31: "jumper",
    32: "ray",
    33: "v2ray",
    34: "goldfish",
    35: "turretred",
    36: "turretpurple",
    37: "flipplane",
    38: "flipplane_orange",
    39: "bomber",
    40: "squidyellow",
    41: "squidgreen",
    42: "squidcan",
    43: "squidcangreen",
    44: "yellowie",
    45: "greenie",
    46: "reddie",
    47: "gunship",
    48: "lasership",
    49: "flameship",
    50: "homingship",
    51: "car",
    52: "gunboat",
    53: "missileboat",
    54: "flameboat",
    55: "boss1",
    56: "boss2",
    57: "unknownEnemy57",
    58: "boss2_intro",
    59: "unknownEnemy59",
    60: "boss3",
    61: "unknownEnemy61CRASH",
    62: "boss4",
    63: "boss5",
    64: "boss5_unknown",
    65: "boss5_intro",
    66: "boss6",
    67: "unknownEnemy67",
    68: "unknownEnemy68CRASH",
    69: "unknownEnemy69CRASH",
    70: "worm",
    71: "eyeball",
    72: "blob",
    73: "rollship",
    74: "chicken",
    75: "bug",
    76: "tonsil",
    77: "virus",
    78: "spinner",
    79: "fang",
    80: "squid",
    81: "podship",
    82: "miniserpent"
}

ENEMY_ARG_NAMES = {
    19: ["xOffset", "yOffset"],
    20: ["yPos"],
    33: ["yPos", "arg3", "ySpeed"],
    35: ["xPos", "yTarget"],
    36: ["xPos", "yTarget"],
    37: ["yPos"],
    38: ["yPos"],
    39: ["yPos"],
    40: ["yPos"],
    41: ["yPos"],
    42: ["yPos"],
    43: ["yPos"],
    44: ["yPos"],
    45: ["yPos"],
    46: ["yPos"],
    47: ["yPos"],
    48: ["yPos"],
    49: ["yPos"],
    50: ["yPos"],
    51: ["type", "link"],
    52: ["direction"],
    54: ["direction"],
    71: ["yPos"],
    72: ["yPos"],
    79: ["direction"],
    81: ["yPos"],
}

SCENERY_NAMES = {
    1: "cloud",
    2: "unknownScenery2",
    3: "arch",
    4: "pylon",
    5: "telegraph",
    6: "buoy",
    7: "buoy_row",
    8: "windmill",
    9: "volcano",
    10: "unknownScenery10",
    11: "waterfall",
    12: "unknownScenery12",
    13: "boat",
    14: "boatfar",
    15: "unknownScenery15",
    16: "building",
    17: "tank",
    18: "parrot",
    19: "bird",
    20: "birdred",
    21: "birdyellow",
    22: "icbm",
    23: "yellowie",
    24: "yellowie2",
    25: "greenie",
    26: "reddie",
    27: "roof_start",
    28: "roof_end",
    29: "unknownScenery29",
    30: "last_start",
    31: "unknownScenery31",
    32: "greenhead",
    33: "mine",
    34: "nuxship",
    35: "unknownScenery35",
    36: "tonsil",
    37: "ulcer",
    38: "eyeball",
    39: "podship"
}

SCENERY_ARG_NAMES = {
    1: ["sprite", "xPos"],
    6: ["layer"],
    8: ["layer"],
    11: ["layer"],
    18: ["sprite"],
    22: ["xOffset", "yOffset", "launchDelay"],
    34: ["xOffset", "yOffset"]
}