ACTION_NAMES = {
    0: "none",
    1: "wait",
    2: "minplayers",
    3: "maxplayers",
    4: "endarea",
    5: "endlevel",
    6: "restart",
    7: "sky",
    8: "water",
    9: "lava",
    10: "wateryellow",
    11: "snow",
    12: "soot",
    13: "rain",
    14: "planet",
    15: "layerblock",
    16: "layerunblock",
    17: "layerrange",
    18: "layercue",
    19: "layerwait",
    20: "layerreset",
    21: "wave",
    22: "enemy",
    23: "scenery",
    24: "coins",
    25: "x2",
    26: "pods",
    27: "shield",
    28: "life",
    29: "lightning"
}

ACTION_ARG_NAMES = {
    2: ["players"],
    3: ["players"],
    7: ["startPoint", "scrollSpeed"],
    8: ["type"],
    9: ["type"],
    10: ["type"],
    11: ["intensity"],
    12: ["intensity"],
    13: ["intensity"],
    14: ["sprite", "xPos", "yPos", "ySpeed"],
    15: ["layer"],
    16: ["layer"],
    17: ["layer", "tileMin", "tileMax"],
    18: ["layer", "tile"],
    21: ["object", "formation", "yPos", "bonus"],
    22: ["object"],
    23: ["object"]
}

ENEMY_NAMES = {
    0: "none",
    1: "bullet",
    2: "flame",
    3: "missile",
    4: "laser",
    5: "orb",
    6: "glob",
    7: "bomb",
    8: "bombfrag",
    9: "mine",
    10: "rock",
    11: "arch",
    12: "pylon",
    13: "telegraph",
    14: "lava",
    15: "buoy",
    16: "dish",
    17: "building",
    18: "tank",
    19: "wallgun",
    20: "icbm",
    21: "domeship",
    22: "domeship2",
    23: "saucer",
    24: "saucer2",
    25: "saucerred",
    26: "zipper",
    27: "fish",
    28: "fishred",
    29: "homingfish",
    30: "horseshoe",
    31: "jumper",
    32: "ray",
    33: "v2ray",
    34: "goldfish",
    35: "hovergun",
    36: "hoverlauncher",
    37: "flipplane",
    38: "flipplaneorange",
    39: "bomber",
    40: "lasersquid",
    41: "gunsquid",
    42: "lightningsquid",
    43: "bombsquid",
    44: "yellowie",
    45: "greenie",
    46: "reddie",
    47: "gunship",
    48: "lasership",
    49: "flameship",
    50: "homingship",
    51: "car",
    52: "gunboat",
    53: "missileboat",
    54: "flameboat",
    55: "boss1",
    56: "boss2",
    57: "boss2seg",
    58: "boss2flyby",
    59: "boss2segflyby",
    60: "boss3",
    61: "boss3base",
    62: "boss4",
    63: "boss5",
    64: "boss5seg",
    65: "boss5enter",
    66: "boss6",
    67: "boss6base",
    68: "boss6arm",
    69: "boss6eye",
    70: "worm",
    71: "eyeball",
    72: "blob",
    73: "rollship",
    74: "chicken",
    75: "bug",
    76: "tonsil",
    77: "virus",
    78: "spinner",
    79: "fang",
    80: "squid",
    81: "podship",
    82: "miniserpent",
    83: "miniserpentseg"
}

ENEMY_ARG_NAMES = {
    1: ["xPos", "yPos", "angle", "speed"],
    2: ["xPos", "yPos", "angle", "speed"],
    3: ["xPos", "yPos", "angle", "speed"],
    4: ["xPos", "yPos", "angle", "speed"],
    5: ["xPos", "yPos", "angle", "speed"],
    6: ["xPos", "yPos", "angle", "speed"],
    7: ["xPos", "yPos", "angle", "speed"],
    8: ["xPos", "yPos", "angle", "speed"],
    10: ["xPos", "yPos"],
    19: ["xOffset", "yOffset"],
    20: ["yPos"],
    33: ["yPos", "arg3", "ySpeed"],
    35: ["xPos", "yTarget"],
    36: ["xPos", "yTarget"],
    37: ["yPos"],
    38: ["yPos"],
    39: ["yPos"],
    40: ["yPos"],
    41: ["yPos"],
    42: ["yPos"],
    43: ["yPos"],
    44: ["yPos"],
    45: ["yPos"],
    46: ["yPos"],
    47: ["yPos"],
    48: ["yPos"],
    49: ["yPos"],
    50: ["yPos"],
    51: ["type", "link"],
    52: ["direction"],
    54: ["direction"],
    71: ["yPos"],
    72: ["yPos"],
    79: ["direction"],
    81: ["yPos"]
}

SCENERY_NAMES = {
    0: "none",
    1: "cloud",
    2: "wheel",
    3: "arch",
    4: "pylon",
    5: "telegraph",
    6: "buoy",
    7: "buoyline",
    8: "windmill",
    9: "volcano",
    10: "rock",
    11: "waterfall",
    12: "splash",
    13: "boat",
    14: "boatfar",
    15: "wallgun",
    16: "building",
    17: "tank",
    18: "parrot",
    19: "bird",
    20: "birdred",
    21: "birdyellow",
    22: "icbm",
    23: "yellowie",
    24: "yellowie2",
    25: "greenie",
    26: "reddie",
    27: "roof",
    28: "roofend",
    29: "roofbit",
    30: "last",
    31: "lastbit",
    32: "greenhead",
    33: "mine",
    34: "nuxship",
    35: "krider",
    36: "tonsil",
    37: "ulcer",
    38: "eyeball",
    39: "podship"
}

SCENERY_ARG_NAMES = {
    1: ["sprite", "xPos"],
    6: ["layer"],
    8: ["layer"],
    11: ["layer"],
    18: ["sprite"],
    22: ["xOffset", "yOffset", "launchDelay"],
    34: ["xOffset", "yOffset"]
}